# -*- coding: utf-8 -*-
"""AgriBD Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUzDgMlWkxVM1CT2rwSVLZABq5lJA65m
"""

# ============================================================
# EXPLAINABLE DEEP LEARNING MODEL FOR EXTREME RAINFALL
# PREDICTION AND AGRICULTURAL RISK ASSESSMENT
# Bangladesh Weather Dataset
# ============================================================

# ─────────────────────────────────────────────
# STEP 1: Install Libraries
# ─────────────────────────────────────────────
# Run this in your terminal or Colab cell:
# !pip install numpy pandas matplotlib scikit-learn tensorflow shap seaborn kagglehub -q


# ─────────────────────────────────────────────
# STEP 2: Import Libraries
# ─────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error,
    r2_score, confusion_matrix, classification_report
)

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Dense, Conv1D, LSTM,
    Bidirectional, Dropout, GlobalAveragePooling1D
)

print(" All libraries imported successfully!")


# ─────────────────────────────────────────────
# STEP 3: Load Dataset
# ─────────────────────────────────────────────
import kagglehub
import os

# Download latest version of dataset
path = kagglehub.dataset_download("yakinrubaiat/bangladesh-weather-dataset")
print("Dataset downloaded to:", path)

# Check files inside downloaded folder
files = os.listdir(path)
print("Files found:", files)

# Auto-load first CSV file
csv_file = [f for f in files if f.endswith(".csv")][0]
file_path = os.path.join(path, csv_file)

df = pd.read_csv(file_path)
print(" Loaded file:", file_path)
print("Shape:", df.shape)
df.head()


# ─────────────────────────────────────────────
# STEP 4: Select Required Columns
# ─────────────────────────────────────────────
df = df[['Year', 'Month', 'tem', 'rain']]
df.columns = ['year', 'month', 'temperature', 'rainfall']

print(" Columns selected:", df.columns.tolist())
print(df.head())

# Dataset Overview Plot
plt.figure(figsize=(12, 4))
plt.plot(df['rainfall'], label='Rainfall', alpha=0.7)
plt.plot(df['temperature'], label='Temperature', alpha=0.7)
plt.legend()
plt.title("Raw Climate Data Overview")
plt.xlabel("Index")
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 5: Sort Data
# ─────────────────────────────────────────────
df = df.sort_values(['year', 'month']).reset_index(drop=True)
print(" Data sorted by Year and Month")

# Monthly Rainfall Trend
monthly_rain = df.groupby('month')['rainfall'].mean()

plt.figure(figsize=(8, 4))
plt.plot(monthly_rain.index, monthly_rain.values, marker='o', color='steelblue')
plt.title("Average Monthly Rainfall Pattern")
plt.xlabel("Month")
plt.ylabel("Average Rainfall")
plt.xticks(range(1, 13), ['Jan','Feb','Mar','Apr','May','Jun',
                           'Jul','Aug','Sep','Oct','Nov','Dec'])
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 6: Handle Missing Values
# ─────────────────────────────────────────────
print("Missing values before:", df.isnull().sum().sum())
df = df.ffill()   # Updated: replaces deprecated fillna(method='ffill')
print("Missing values after:", df.isnull().sum().sum())
print(" Missing values handled!")


# ─────────────────────────────────────────────
# STEP 7: Normalize Data
# ─────────────────────────────────────────────
scaler = MinMaxScaler()
df[['temperature', 'rainfall']] = scaler.fit_transform(
    df[['temperature', 'rainfall']]
)
print(" Data normalized with MinMaxScaler")

# Normalized Data Visualization
plt.figure(figsize=(12, 4))
plt.plot(df['temperature'], label='Temperature', alpha=0.7)
plt.plot(df['rainfall'], label='Rainfall', alpha=0.7)
plt.legend()
plt.title("Normalized Climate Variables")
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 8: Feature Engineering
# ─────────────────────────────────────────────
df['rain_ma3']  = df['rainfall'].rolling(3).mean().fillna(0)
df['temp_ma3']  = df['temperature'].rolling(3).mean().fillna(0)

# NEW: Additional engineered features
df['rain_ma6']      = df['rainfall'].rolling(6).mean().fillna(0)
df['temp_rain_ratio'] = df['temperature'] / (df['rainfall'] + 1e-5)
df['rainfall_lag1'] = df['rainfall'].shift(1).fillna(0)
df['rainfall_lag2'] = df['rainfall'].shift(2).fillna(0)

print(" Feature engineering complete!")
print("Features:", df.columns.tolist())


# ─────────────────────────────────────────────
# STEP 9: Create Time-Series Sequences
# ─────────────────────────────────────────────
def create_sequences(data, step=6):
    X, y = [], []
    for i in range(len(data) - step):
        X.append(data[i:i+step])
        y.append(data[i+step][1])   # rainfall target (index 1)
    return np.array(X), np.array(y)

data = df[['temperature', 'rainfall']].values

X, y = create_sequences(data, step=6)
print(f" Sequences created → X: {X.shape}, y: {y.shape}")


# ─────────────────────────────────────────────
# STEP 10: Train-Test Split
# ─────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)
print(f" Train size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")


# ─────────────────────────────────────────────
# STEP 11: Reshape for CNN
# ─────────────────────────────────────────────
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 2))
X_test  = X_test.reshape((X_test.shape[0],  X_test.shape[1],  2))
print(f" Reshaped → X_train: {X_train.shape}, X_test: {X_test.shape}")


# ─────────────────────────────────────────────
# STEP 12: Build CNN + BiLSTM + Attention Model
# ─────────────────────────────────────────────
inputs = Input(shape=(X_train.shape[1], X_train.shape[2]))

x = Conv1D(64, 2, activation='relu')(inputs)

x = Bidirectional(LSTM(64, return_sequences=True))(x)

attention = tf.keras.layers.Attention()([x, x])

x = GlobalAveragePooling1D()(attention)

x = Dropout(0.3)(x)

x = Dense(64, activation='relu')(x)

output = Dense(1)(x)

model = Model(inputs, output)
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()
print(" Model built successfully!")


# ─────────────────────────────────────────────
# STEP 13: Train Model
# ─────────────────────────────────────────────
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=30,
    batch_size=32,
    verbose=1
)
print(" Model training complete!")

# Training vs Validation Loss
plt.figure(figsize=(8, 4))
plt.plot(history.history['loss'],     label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("Model Training Performance")
plt.xlabel("Epochs")
plt.ylabel("Loss (MSE)")
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 14: Predictions
# ─────────────────────────────────────────────
y_pred = model.predict(X_test)
print(f" Predictions done → shape: {y_pred.shape}")


# ─────────────────────────────────────────────
# STEP 15: Evaluation Metrics  ← UPDATED (R² added)
# ─────────────────────────────────────────────
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae  = mean_absolute_error(y_test, y_pred)
r2   = r2_score(y_test, y_pred)          # NEW

print("=" * 40)
print(" MODEL EVALUATION METRICS")
print("=" * 40)
print(f"  RMSE  : {rmse:.4f}")
print(f"  MAE   : {mae:.4f}")
print(f"  R²    : {r2:.4f}")             # NEW
print("=" * 40)


# ─────────────────────────────────────────────
# STEP 16: Extreme Rainfall Classification
# ─────────────────────────────────────────────
def classify(x):
    if x < 0.3:
        return 0   # Low
    elif x < 0.7:
        return 1   # Medium
    else:
        return 2   # Extreme

y_test_class = np.array([classify(i)    for i in y_test])
y_pred_class = np.array([classify(i[0]) for i in y_pred])

print(" Rainfall classes assigned (0=Low, 1=Medium, 2=Extreme)")


# ─────────────────────────────────────────────
# STEP 17: Confusion Matrix & Classification Report
# ─────────────────────────────────────────────
print("\n Confusion Matrix:")
print(confusion_matrix(y_test_class, y_pred_class))

print("\n Classification Report:")
print(classification_report(
    y_test_class, y_pred_class,
    target_names=['Low', 'Medium', 'Extreme']
))

# Confusion Matrix Heatmap
cm = confusion_matrix(y_test_class, y_pred_class)
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Low', 'Medium', 'Extreme'],
    yticklabels=['Low', 'Medium', 'Extreme']
)
plt.title("Rainfall Risk Confusion Matrix")
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 18: SHAP Explainability  ← UPDATED (feature names added)
# ─────────────────────────────────────────────
import shap

# Wrapper function for Keras model
def model_predict_wrapper(x_flat):
    timesteps = X_train.shape[1]
    features  = X_train.shape[2]
    x_reshaped = x_flat.reshape(-1, timesteps, features)
    return model.predict(x_reshaped, verbose=0)

# Flatten arrays for SHAP
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat  = X_test.reshape(X_test.shape[0],   -1)

# Feature names for each timestep   ← NEW
feature_names = []
for t in range(X_train.shape[1]):       # 6 timesteps
    feature_names.append(f'Temp_t-{6 - t}')
    feature_names.append(f'Rain_t-{6 - t}')

print("Feature names:", feature_names)

# KernelExplainer — more stable for CNN/LSTM   ← UPDATED
print(" Running SHAP (this may take a few minutes)...")
explainer   = shap.KernelExplainer(model_predict_wrapper, X_train_flat[:50])
shap_values = explainer.shap_values(X_test_flat[:50])

# SHAP Summary Plot with feature names   ← UPDATED
plt.figure()
shap.summary_plot(
    shap_values, X_test_flat[:50],
    feature_names=feature_names,
    show=True
)

# SHAP Bar Plot (global feature importance)   ← NEW
plt.figure()
shap.summary_plot(
    shap_values, X_test_flat[:50],
    feature_names=feature_names,
    plot_type='bar',
    show=True
)
print(" SHAP explainability done!")


# ─────────────────────────────────────────────
# STEP 19: Risk Level Prediction Output
# ─────────────────────────────────────────────
def risk_level(x):
    if x < 0.3:
        return "Low Risk"
    elif x < 0.6:
        return "Medium Risk"
    elif x < 0.8:
        return "High Risk"
    else:
        return "Extreme Risk"

risk_predictions = [risk_level(i[0]) for i in y_pred]
print("\n Risk Level Predictions (first 20):")
print(risk_predictions[:20])


# ─────────────────────────────────────────────
# STEP 20: Actual vs Predicted Visualization
# ─────────────────────────────────────────────
plt.figure(figsize=(12, 4))
plt.plot(y_test[:100],       label='Actual',    linewidth=2)
plt.plot(y_pred[:100],       label='Predicted', linewidth=2, linestyle='--')
plt.legend()
plt.title("Actual vs Predicted Rainfall (First 100 Test Samples)")
plt.xlabel("Time Steps")
plt.ylabel("Normalized Rainfall")
plt.tight_layout()
plt.show()

# Full test set view
plt.figure(figsize=(12, 4))
plt.plot(y_test,  label='Actual',    alpha=0.7)
plt.plot(y_pred,  label='Predicted', alpha=0.7)
plt.legend()
plt.title("Rainfall Prediction — Full Test Set")
plt.xlabel("Time Steps")
plt.ylabel("Normalized Rainfall")
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 21: Seasonal Analysis  ← NEW
# ─────────────────────────────────────────────
# Recover month info for the test period
test_months = df['month'].values[len(df) - len(y_test):]

season_df = pd.DataFrame({
    'month':     test_months,
    'actual':    y_test,
    'predicted': y_pred.flatten()
})

season_df['season'] = season_df['month'].map({
    12: 'Winter',      1: 'Winter',      2: 'Winter',
     3: 'Pre-Monsoon', 4: 'Pre-Monsoon', 5: 'Pre-Monsoon',
     6: 'Monsoon',     7: 'Monsoon',     8: 'Monsoon',     9: 'Monsoon',
    10: 'Post-Monsoon',11: 'Post-Monsoon'
})

season_summary = season_df.groupby('season')[['actual', 'predicted']].mean()
print("\n Seasonal Analysis (Mean Normalized Rainfall):")
print(season_summary.round(4))

# Seasonal bar chart
season_summary.plot(kind='bar', figsize=(8, 4), color=['steelblue', 'coral'])
plt.title("Seasonal Actual vs Predicted Rainfall")
plt.ylabel("Mean Normalized Rainfall")
plt.xlabel("Season")
plt.xticks(rotation=30)
plt.legend(['Actual', 'Predicted'])
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 22: Agricultural Risk Assessment  ← NEW
# ─────────────────────────────────────────────
def agricultural_risk_assessment(predicted_rainfall_list):
    """
    Maps predicted rainfall (normalized) →
    agricultural risk category for Bangladesh crops.
    """
    records = []
    for val in predicted_rainfall_list:
        if val < 0.2:
            records.append({
                'Predicted_Rainfall': round(val, 4),
                'Risk_Category':      'Drought Risk ',
                'Affected_Crops':     'Boro Rice, Wheat, Mustard',
                'Season':             'Rabi (Winter)',
                'Recommended_Action': 'Apply irrigation immediately'
            })
        elif val < 0.5:
            records.append({
                'Predicted_Rainfall': round(val, 4),
                'Risk_Category':      'Normal ',
                'Affected_Crops':     'All Crops Safe',
                'Season':             'All Seasons',
                'Recommended_Action': 'Standard farming practices'
            })
        elif val < 0.75:
            records.append({
                'Predicted_Rainfall': round(val, 4),
                'Risk_Category':      'Flood Risk ',
                'Affected_Crops':     'Aus Rice, Jute, Vegetables',
                'Season':             'Kharif (Monsoon)',
                'Recommended_Action': 'Improve drainage, protect seedlings'
            })
        else:
            records.append({
                'Predicted_Rainfall': round(val, 4),
                'Risk_Category':      'Extreme Flood Risk ',
                'Affected_Crops':     'All Crops (severe loss expected)',
                'Season':             'Peak Monsoon',
                'Recommended_Action': 'Emergency protocol — evacuate crops'
            })
    return pd.DataFrame(records)

agri_df = agricultural_risk_assessment([i[0] for i in y_pred])

print("\n AGRICULTURAL RISK ASSESSMENT (First 20 Predictions):")
print(agri_df.head(20).to_string(index=False))

# Risk category distribution pie chart
risk_counts = agri_df['Risk_Category'].value_counts()
plt.figure(figsize=(7, 6))
plt.pie(
    risk_counts.values,
    labels=risk_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=['gold', 'lightgreen', 'cornflowerblue', 'tomato']
)
plt.title("Agricultural Risk Category Distribution\n(Based on Predicted Rainfall)")
plt.tight_layout()
plt.show()

# Risk category count bar chart
plt.figure(figsize=(8, 4))
risk_counts.plot(kind='bar', color=['gold', 'lightgreen', 'cornflowerblue', 'tomato'])
plt.title("Agricultural Risk Category Counts")
plt.ylabel("Number of Predictions")
plt.xlabel("Risk Category")
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()


# ─────────────────────────────────────────────
# STEP 23: Future Forecasting  ← NEW
# ─────────────────────────────────────────────
print("\n Forecasting next 12 months of rainfall...")

# Use last 6 known data points as the seed sequence
last_sequence = data[-6:].copy()     # shape (6, 2)
future_preds  = []

for _ in range(12):
    seq_input  = last_sequence.reshape(1, 6, 2)
    next_val   = model.predict(seq_input, verbose=0)[0][0]
    future_preds.append(next_val)
    # Slide window: drop oldest, append new prediction
    new_row        = np.array([[last_sequence[-1, 0], next_val]])  # keep last temp
    last_sequence  = np.vstack([last_sequence[1:], new_row])

months_label = ['M+1','M+2','M+3','M+4','M+5','M+6',
                'M+7','M+8','M+9','M+10','M+11','M+12']

plt.figure(figsize=(10, 4))
plt.plot(months_label, future_preds, marker='o', color='darkorange', linewidth=2)
plt.fill_between(months_label, future_preds, alpha=0.2, color='orange')
plt.title("Future 12-Month Rainfall Forecast (Normalized)")
plt.ylabel("Predicted Normalized Rainfall")
plt.xlabel("Future Months")
plt.tight_layout()
plt.show()

# Agricultural risk for future predictions
future_agri = agricultural_risk_assessment(future_preds)
future_agri.insert(0, 'Month', months_label)
print("\n Future 12-Month Agricultural Risk Forecast:")
print(future_agri.to_string(index=False))


# ─────────────────────────────────────────────
# STEP 24: Final Summary Dashboard  ← NEW
# ─────────────────────────────────────────────
print("\n" + "=" * 55)
print("   FINAL RESEARCH SUMMARY DASHBOARD")
print("=" * 55)
print(f"  Model      : CNN + BiLSTM + Attention")
print(f"  Dataset    : Bangladesh Weather Dataset")
print(f"  Train size : {X_train.shape[0]} samples")
print(f"  Test size  : {X_test.shape[0]}  samples")
print("-" * 55)
print(f"  RMSE       : {rmse:.4f}")
print(f"  MAE        : {mae:.4f}")
print(f"  R² Score   : {r2:.4f}")
print("-" * 55)
print("  Extreme Rainfall Classification:")
print(classification_report(
    y_test_class, y_pred_class,
    target_names=['Low', 'Medium', 'Extreme'], digits=4
))
print("-" * 55)
print("  Agricultural Risk Distribution:")
print(agri_df['Risk_Category'].value_counts().to_string())
print("=" * 55)
print(" Research pipeline complete!")